# Generated by Django 2.0.5 on 2018-09-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookNumber', models.IntegerField(max_length=10)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=50)),
                ('Pages', models.IntegerField(max_length=5)),
                ('Publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
