# Generated by Django 2.0.5 on 2018-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='BookNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='Pages',
            field=models.IntegerField(),
        ),
    ]
