# Generated by Django 2.0.5 on 2018-09-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180918_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookInfo',
            new_name='Catalogue',
        ),
    ]
