# Generated by Django 2.0.2 on 2018-10-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
