# Generated by Django 2.0.2 on 2018-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='batch',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
